// Auto-generated by TableDataBaseGenerator
using Fox;


namespace Fox.Config
{
    public partial class ExcelData
    {
    public ExcelTable<Language_CNList, Language_CN> Language_CNTable =  new ExcelTable<Language_CNList, Language_CN>();

    public ExcelTable<Language_ENList, Language_EN> Language_ENTable =  new ExcelTable<Language_ENList, Language_EN>();


    }
}
