// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Fox.Config
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Language_CN : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static Language_CN GetRootAsLanguage_CN(ByteBuffer _bb) { return GetRootAsLanguage_CN(_bb, new Language_CN()); }
  public static Language_CN GetRootAsLanguage_CN(ByteBuffer _bb, Language_CN obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Language_CN __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int ID { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Chinese { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetChineseBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetChineseBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetChineseArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<Fox.Config.Language_CN> CreateLanguage_CN(FlatBufferBuilder builder,
      int ID = 0,
      StringOffset ChineseOffset = default(StringOffset)) {
    builder.StartTable(2);
    Language_CN.AddChinese(builder, ChineseOffset);
    Language_CN.AddID(builder, ID);
    return Language_CN.EndLanguage_CN(builder);
  }

  public static void StartLanguage_CN(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddID(FlatBufferBuilder builder, int iD) { builder.AddInt(0, iD, 0); }
  public static void AddChinese(FlatBufferBuilder builder, StringOffset chineseOffset) { builder.AddOffset(1, chineseOffset.Value, 0); }
  public static Offset<Fox.Config.Language_CN> EndLanguage_CN(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Fox.Config.Language_CN>(o);
  }

  public static VectorOffset CreateSortedVectorOfLanguage_CN(FlatBufferBuilder builder, Offset<Language_CN>[] offsets) {
    Array.Sort(offsets,
      (Offset<Language_CN> o1, Offset<Language_CN> o2) =>
        new Language_CN().__assign(builder.DataBuffer.Length - o1.Value, builder.DataBuffer).ID.CompareTo(new Language_CN().__assign(builder.DataBuffer.Length - o2.Value, builder.DataBuffer).ID));
    return builder.CreateVectorOfTables(offsets);
  }

  public static Language_CN? __lookup_by_key(int vectorLocation, int key, ByteBuffer bb) {
    Language_CN obj_ = new Language_CN();
    int span = bb.GetInt(vectorLocation - 4);
    int start = 0;
    while (span != 0) {
      int middle = span / 2;
      int tableOffset = Table.__indirect(vectorLocation + 4 * (start + middle), bb);
      obj_.__assign(tableOffset, bb);
      int comp = obj_.ID.CompareTo(key);
      if (comp > 0) {
        span = middle;
      } else if (comp < 0) {
        middle++;
        start += middle;
        span -= middle;
      } else {
        return obj_;
      }
    }
    return null;
  }
}


static public class Language_CNVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*ID*/, 4 /*int*/, 4, false)
      && verifier.VerifyString(tablePos, 6 /*Chinese*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
