// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Fox.Config
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Language_ENList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static Language_ENList GetRootAsLanguage_ENList(ByteBuffer _bb) { return GetRootAsLanguage_ENList(_bb, new Language_ENList()); }
  public static Language_ENList GetRootAsLanguage_ENList(ByteBuffer _bb, Language_ENList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyLanguage_ENList(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, Language_ENListVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Language_ENList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Fox.Config.Language_EN? Items(int j) { int o = __p.__offset(4); return o != 0 ? (Fox.Config.Language_EN?)(new Fox.Config.Language_EN()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ItemsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
  public Fox.Config.Language_EN? ItemsByKey(int key) { int o = __p.__offset(4); return o != 0 ? Fox.Config.Language_EN.__lookup_by_key(__p.__vector(o), key, __p.bb) : null; }

  public static Offset<Fox.Config.Language_ENList> CreateLanguage_ENList(FlatBufferBuilder builder,
      VectorOffset itemsOffset = default(VectorOffset)) {
    builder.StartTable(1);
    Language_ENList.AddItems(builder, itemsOffset);
    return Language_ENList.EndLanguage_ENList(builder);
  }

  public static void StartLanguage_ENList(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddItems(FlatBufferBuilder builder, VectorOffset itemsOffset) { builder.AddOffset(0, itemsOffset.Value, 0); }
  public static VectorOffset CreateItemsVector(FlatBufferBuilder builder, Offset<Fox.Config.Language_EN>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateItemsVectorBlock(FlatBufferBuilder builder, Offset<Fox.Config.Language_EN>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateItemsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<Fox.Config.Language_EN>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateItemsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<Fox.Config.Language_EN>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartItemsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Fox.Config.Language_ENList> EndLanguage_ENList(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Fox.Config.Language_ENList>(o);
  }
  public static void FinishLanguage_ENListBuffer(FlatBufferBuilder builder, Offset<Fox.Config.Language_ENList> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedLanguage_ENListBuffer(FlatBufferBuilder builder, Offset<Fox.Config.Language_ENList> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class Language_ENListVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfTables(tablePos, 4 /*Items*/, Fox.Config.Language_ENVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
