// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Fox.Config
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Language_EN : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static Language_EN GetRootAsLanguage_EN(ByteBuffer _bb) { return GetRootAsLanguage_EN(_bb, new Language_EN()); }
  public static Language_EN GetRootAsLanguage_EN(ByteBuffer _bb, Language_EN obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Language_EN __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int ID { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string English { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetEnglishBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetEnglishBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetEnglishArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<Fox.Config.Language_EN> CreateLanguage_EN(FlatBufferBuilder builder,
      int ID = 0,
      StringOffset EnglishOffset = default(StringOffset)) {
    builder.StartTable(2);
    Language_EN.AddEnglish(builder, EnglishOffset);
    Language_EN.AddID(builder, ID);
    return Language_EN.EndLanguage_EN(builder);
  }

  public static void StartLanguage_EN(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddID(FlatBufferBuilder builder, int iD) { builder.AddInt(0, iD, 0); }
  public static void AddEnglish(FlatBufferBuilder builder, StringOffset englishOffset) { builder.AddOffset(1, englishOffset.Value, 0); }
  public static Offset<Fox.Config.Language_EN> EndLanguage_EN(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Fox.Config.Language_EN>(o);
  }

  public static VectorOffset CreateSortedVectorOfLanguage_EN(FlatBufferBuilder builder, Offset<Language_EN>[] offsets) {
    Array.Sort(offsets,
      (Offset<Language_EN> o1, Offset<Language_EN> o2) =>
        new Language_EN().__assign(builder.DataBuffer.Length - o1.Value, builder.DataBuffer).ID.CompareTo(new Language_EN().__assign(builder.DataBuffer.Length - o2.Value, builder.DataBuffer).ID));
    return builder.CreateVectorOfTables(offsets);
  }

  public static Language_EN? __lookup_by_key(int vectorLocation, int key, ByteBuffer bb) {
    Language_EN obj_ = new Language_EN();
    int span = bb.GetInt(vectorLocation - 4);
    int start = 0;
    while (span != 0) {
      int middle = span / 2;
      int tableOffset = Table.__indirect(vectorLocation + 4 * (start + middle), bb);
      obj_.__assign(tableOffset, bb);
      int comp = obj_.ID.CompareTo(key);
      if (comp > 0) {
        span = middle;
      } else if (comp < 0) {
        middle++;
        start += middle;
        span -= middle;
      } else {
        return obj_;
      }
    }
    return null;
  }
}


static public class Language_ENVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*ID*/, 4 /*int*/, 4, false)
      && verifier.VerifyString(tablePos, 6 /*English*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
